# Generated by Django 4.2.26 on 2026-01-20 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_usersubmissions'),
        ('contributors', '0003_make_email_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='contribution',
            field=models.TextField(blank=True, help_text='Describe what you did in the PostgreSQL community', null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='ctype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributors.contributortype', verbose_name='Contributor Type'),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('badge', models.CharField(help_text='Title of this badge, e.g. "PGConf.EU 2025 Speaker".', max_length=32, unique=True)),
                ('description', models.TextField(blank=True, help_text='What did the people do who contributed here?', null=True)),
                ('url', models.URLField(blank=True, help_text='URL for this contribution, e.g. the conference homepage. (Leave blank when there is no URL.)', max_length=100, null=True, verbose_name='Contribution URL')),
                ('image', models.CharField(blank=True, help_text='Badge images should be square (usually shown at 150x150 pixels). When left blank, the Slony logo will be used. External URLs work, but preferably the image should be hosted on postgresql.org. Mail the Contributors team to have your image added.', max_length=100, null=True, verbose_name='Path to contribution image')),
                ('contact', models.CharField(blank=True, help_text='Contact address (email, URL, other) for people who want to be added as badge holder', max_length=100, null=True, verbose_name='Contact address')),
                ('sortorder', models.IntegerField(blank=True, default=100, null=True)),
                ('holders', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(help_text='If no organisations are listed here, please check the <a href="/account/orglist/">organisation list</a> and contact the organisation manager or <a href="mailto:webmaster@postgresql.org">webmaster@postgresql.org</a> if no managers are listed. If your organisation is not listed, you can <a href="/account/edit/organisations/">create it</a>.', on_delete=django.db.models.deletion.CASCADE, to='core.organisation', verbose_name='Organisation')),
            ],
            options={
                'ordering': ('sortorder', 'badge'),
            },
        ),
    ]
