# Generated by Django 4.2.26 on 2025-11-13 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_communityauthsite_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Badge name (e.g., 'First Commit', 'First Review')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this badge represents')),
                ('icon', models.CharField(default='fa-trophy', help_text="Font Awesome icon class (e.g., 'fa-trophy', 'fa-star')", max_length=50)),
                ('color', models.CharField(default='#FFD700', help_text="Badge color in hex format (e.g., '#FFD700' for gold)", max_length=20)),
                ('order', models.IntegerField(default=100, help_text='Display order (lower numbers show first)')),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Optional note about this badge award')),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='account.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-awarded_at',),
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
