# Generated by Django 4.2.26 on 2025-11-14 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_version_docsgit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_communityauthsite_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Badge name (e.g., 'PGConf.dev 2025 Volunteer', 'Postgres 18 Contributor')", max_length=200)),
                ('description', models.TextField(help_text='What this badge represents and how to earn it')),
                ('icon', models.CharField(default='fa-trophy', help_text="Font Awesome icon class (e.g., 'fa-trophy', 'fa-star', 'fa-award')", max_length=50)),
                ('color', models.CharField(default='#FFD700', help_text="Badge color in hex format (e.g., '#FFD700' for gold)", max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Whether users can currently claim this badge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(help_text='Organization that created and manages this badge', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.organisation')),
            ],
            options={
                'ordering': ('-created_at', 'name'),
                'unique_together': {('organisation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BadgeClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, help_text="User's message explaining why they deserve this badge")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text="Reviewer's note about the decision")),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='account.badge')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_claims_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-claimed_at',),
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='account.badge')),
                ('claim', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badge', to='account.badgeclaim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-awarded_at',),
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
