# Generated by Django 4.2.26 on 2025-11-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_badge_claim_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='approved',
            field=models.BooleanField(default=False, help_text='Approved by site administrator (must be approved before users can claim)'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='active',
            field=models.BooleanField(default=True, help_text='Site admin only: Whether users can currently claim this badge'),
        ),
    ]
